%% ============================================================
%  Quantitative comparison table for Fig. 17 and Fig. 18
%  Columns:
%  Method | Meta-task setting | Initial RTHS | Adaptive RTHS
%  Total training RTHS | Independent validation RTHS | Final RMSE | Final R2
% =============================================================

clear;
clc;

%% Basic settings
N_init = 5;          % initial LHS RTHS samples
N_val  = 25;         % independent validation RTHS tests
N_max  = 20;
hhm    = 1;

outDir = './table';
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

%% Adaptive RTHS counts used in your plotting code
N_maxg    = 15;   % ASGP

N_maxcm1  = 16;   % AMT-ASCOGP, Meta-task 1
N_maxcm2  = 13;   % AMT-ASCOGP, Meta-task 2
N_maxcm3  = 14;   % AMT-ASCOGP, Meta-task 3

N_maxmms1 = 13;   % SMT-ASMLGP, Meta-task 1
N_maxmms2 = 18;   % SMT-ASMLGP, Meta-task 2
N_maxmms3 = 13;   % SMT-ASMLGP, Meta-task 3

N_maxmm1  = 10;   % AMT-ASMLGP, Meta-task 1
N_maxmm2  = 10;   % AMT-ASMLGP, Meta-task 2
N_maxmm3  = 11;   % AMT-ASMLGP, Meta-task 3

%% File list and variable names
rows = {};

% -------------------------
% ASGP
% -------------------------
rows(end+1,:) = { ...
    'ASGP', ...
    'None', ...
    fullfile('result1','AK_v3_exp', ...
    ['pyAK_2story_2ue_v3_expr_', num2str(N_max), '.mat']), ...
    'RMSEgp', ...
    'RRgp', ...
    N_maxg};

% -------------------------
% AMT-ASCOGP
% -------------------------
rows(end+1,:) = { ...
    'AMT-ASCOGP', ...
    'Meta-task 1', ...
    fullfile('result1','AcK_v3_25', ...
    ['Ack_2story_2ue_v3_exp', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEcgp', ...
    'RRcgp', ...
    N_maxcm1};

rows(end+1,:) = { ...
    'AMT-ASCOGP', ...
    'Meta-task 2', ...
    fullfile('result1','AcK_v3_25', ...
    ['Ack_2story_2ue_v3_exp_m1', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEcgp', ...
    'RRcgp', ...
    N_maxcm2};

rows(end+1,:) = { ...
    'AMT-ASCOGP', ...
    'Meta-task 3', ...
    fullfile('result1','AcK_v3_25', ...
    ['Ack_2story_2ue_v3_exp_m2', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEcgp', ...
    'RRcgp', ...
    N_maxcm3};

% -------------------------
% SMT-ASMLGP
% -------------------------
rows(end+1,:) = { ...
    'LMT-ASMLGP', ...
    'Meta-task 1', ...
    fullfile('result1','AMLGP_v3_25', ...
    ['ASmlgp_32_2story_2ue_v3_exp', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEmlgp', ...
    'RRmlgp', ...
    N_maxmms1};
hhm=1;
rows(end+1,:) = { ...
    'LMT-ASMLGP', ...
    'Meta-task 2', ...
    fullfile('result1','AMLGP_v3_25', ...
    ['ASmlgp_32_2story_2ue_v3_exp_m1', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEmlgp', ...
    'RRmlgp', ...
    N_maxmms2};
hhm=1;
rows(end+1,:) = { ...
    'LMT-ASMLGP', ...
    'Meta-task 3', ...
    fullfile('result1','AMLGP_v3_25', ...
    ['ASmlgp_32_2story_2ue_v3_exp_m2', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEmlgp', ...
    'RRmlgp', ...
    N_maxmms3};

% -------------------------
% AMT-ASMLGP
% -------------------------
rows(end+1,:) = { ...
    'AMT-ASMLGP', ...
    'Meta-task 1', ...
    fullfile('result1','AMLGP_v3_25', ...
    ['Amlgp_2story_2ue_v3_exp', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEmlgp', ...
    'RRmlgp', ...
    N_maxmm1};

rows(end+1,:) = { ...
    'AMT-ASMLGP', ...
    'Meta-task 2', ...
    fullfile('result1','AMLGP_v3_25', ...
    ['Amlgp_2story_2ue_v3_exp_m1', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEmlgp', ...
    'RRmlgp', ...
    N_maxmm2};

rows(end+1,:) = { ...
    'AMT-ASMLGP', ...
    'Meta-task 3', ...
    fullfile('result1','AMLGP_v3_25', ...
    ['Amlgp_2story_2ue_v3_exp_m2', num2str(N_max), '_', num2str(hhm), '.mat']), ...
    'RMSEmlgp', ...
    'RRmlgp', ...
    N_maxmm3};

%% Extract final RMSE and R2
nRow = size(rows,1);

Method = strings(nRow,1);
MetaTaskSetting = strings(nRow,1);
InitialRTHS = N_init * ones(nRow,1);
AdaptiveRTHS = zeros(nRow,1);
TotalTrainingRTHS = zeros(nRow,1);
IndependentValidationRTHS = N_val * ones(nRow,1);
FinalRMSE = nan(nRow,1);
FinalR2 = nan(nRow,1);

for i = 1:nRow

    Method(i) = string(rows{i,1});
    MetaTaskSetting(i) = string(rows{i,2});

    fileName = rows{i,3};
    rmseVar  = rows{i,4};
    r2Var    = rows{i,5};
    nAdapt   = rows{i,6};

    AdaptiveRTHS(i) = nAdapt;
    TotalTrainingRTHS(i) = N_init + nAdapt;

    if ~exist(fileName, 'file')
        warning('File not found: %s', fileName);
        continue;
    end

    S = load(fileName);

    if ~isfield(S, rmseVar)
        warning('Variable %s not found in %s', rmseVar, fileName);
    else
        rmseData = S.(rmseVar);
        FinalRMSE(i) = get_final_value(rmseData, nAdapt);
    end

    if ~isfield(S, r2Var)
        warning('Variable %s not found in %s', r2Var, fileName);
    else
        r2Data = S.(r2Var);
        FinalR2(i) = get_final_value(r2Data, nAdapt);
    end
end

%% Generate result table
ResultTable = table( ...
    Method, ...
    MetaTaskSetting, ...
    InitialRTHS, ...
    AdaptiveRTHS, ...
    TotalTrainingRTHS, ...
    IndependentValidationRTHS, ...
    FinalRMSE, ...
    FinalR2);

% Optional rounding for manuscript display
ResultTable_rounded = ResultTable;
ResultTable_rounded.FinalRMSE = round(ResultTable_rounded.FinalRMSE, 4);
ResultTable_rounded.FinalR2   = round(ResultTable_rounded.FinalR2, 4);

disp(ResultTable_rounded);

%% Save results
writetable(ResultTable, fullfile(outDir, 'validation_performance_table_raw.xlsx'));
writetable(ResultTable_rounded, fullfile(outDir, 'validation_performance_table_rounded.xlsx'));

writetable(ResultTable, fullfile(outDir, 'validation_performance_table_raw.csv'));
writetable(ResultTable_rounded, fullfile(outDir, 'validation_performance_table_rounded.csv'));

%% ------------------------------------------------------------
% Local function
%% ------------------------------------------------------------
function val = get_final_value(data, nAdapt)
    data = data(:);

    if isempty(data)
        val = NaN;
        return;
    end

    % Use the specified convergence/adaptive index when available.
    if numel(data) >= nAdapt
        val = data(nAdapt);
    else
        % Fall back to the last available value.
        val = data(end);
        warning('Data length is smaller than nAdapt. The last available value is used.');
    end
end